name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ls -l
      - run: sudo apt-get update && sudo apt-get install cowsay
      - run: npm clean-install
      - run: npm run lint && npm start
      - run: cat README.md | cowsay